# Introduction to Machine Learning - Final Project
### A Deep Reinforcement Algorithm in an OpenAI Gym Environment

During this final project, we will build a deep neural network and use reinforcement learning to solve a cart and pole balancing problem using OpenAI.  OpenAI Gym is a tookit for developing and comparing reinforcement learning algorithms that was built by OpenAI, a non-profit artificial intelligence research company founded by Elon Musk and Sam Altman.  

## 1. Installing and Loading Libraries

As always, the first step is to download and install all the dependencies.  To install OpenAI Gym, we will use Git. Depending on your operating system, the installation will be slightly different. Installation instructions can be found at:

https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Once Git is installed, we can download and install OpenAI easily using the following commands:


This downloads the bare minimums for the OpenAI Gym environment.  OpenAI Gym contains a wide variety of environments, even Atari games. Some of these environments will need additional dependencies installed.    

We will also need the following python libraries:

* NumPy
* Keras
* Theano
    
Install them using conda or pip.  

## 1.1 Importing libraries

Check that the libraries are installed correctly by running the following import statements

In [4]:
import gym
print(gym.__version__)

0.15.4


In [5]:
import keras
print(keras.__version__)

AssertionError: 

In [6]:
import random
import math
import numpy as np
from collections import deque

## 1.2 OpenAI Gym Environment

The following cells build the 'CartPole-v0' environment that we will use in this project and runs it for twenty episodes.  

In [1]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[ 0.00185908 -0.02656556  0.02757653  0.00288451]
[ 0.00132777 -0.22207192  0.02763422  0.30413902]
[-0.00311367 -0.02735447  0.033717    0.02029778]
[-0.00366076  0.16726813  0.03412295 -0.26155927]
[-3.15398122e-04  3.61886789e-01  2.88917695e-02 -5.43287116e-01]
[ 0.00692234  0.16637098  0.01802603 -0.24164279]
[ 0.01024976  0.36123086  0.01319317 -0.52858576]
[ 0.01747437  0.55616473  0.00262146 -0.81708245]
[ 0.02859767  0.7512507  -0.01372019 -1.10893969]
[ 0.04362268  0.94655024 -0.03589899 -1.40589504]
[ 0.06255369  1.14209895 -0.06401689 -1.70958115]
[ 0.08539567  1.33789545 -0.09820851 -2.02148241]
[ 0.11215358  1.14391847 -0.13863816 -1.76074589]
[ 0.13503195  1.34031089 -0.17385308 -2.09313716]
Episode finished after 14 timesteps
[-0.03440801  0.03410644  0.02152318  0.01858399]
[-0.03372588 -0.16131746  0.02189486  0.31797927]
[-0.03695223  0.03348591  0.02825444  0.03228082]
[-0.03628251  0.22819153  0.02890006 -0.25135533]
[-0.03171868  0.42288912  0.02387295 -0.53478434

[-0.01700505 -0.36781368 -0.00795989  0.44736972]
[-0.02436132 -0.17258004  0.0009875   0.15218835]
[-0.02781292 -0.36771612  0.00403127  0.44518265]
[-0.03516725 -0.56289487  0.01293492  0.73913359]
[-0.04642514 -0.3679539   0.0277176   0.45054936]
[-0.05378422 -0.17323471  0.03672858  0.16673069]
[-0.05724892  0.02134277  0.0400632  -0.11414291]
[-0.05682206  0.21586845  0.03778034 -0.39392186]
[-0.05250469  0.4104345   0.0299019  -0.6744579 ]
[-0.044296    0.6051284   0.01641274 -0.95757835]
[-0.03219343  0.80002586 -0.00273882 -1.24506003]
[-0.01619292  0.99518284 -0.02764002 -1.53859961]
[ 0.00371074  0.80040414 -0.05841202 -1.25466829]
[ 0.01971882  0.99622341 -0.08350538 -1.56505962]
[ 0.03964329  1.19223829 -0.11480657 -1.88257946]
[ 0.06348806  1.38840785 -0.15245816 -2.20857575]
[ 0.09125622  1.19504226 -0.19662968 -1.96654097]
Episode finished after 39 timesteps
[-0.03366319 -0.04524984 -0.03780623 -0.01468572]
[-0.03456819 -0.23980979 -0.03809994  0.26583327]
[-0.03936439 -

[-0.04206831 -0.21415842  0.17875559  0.65155572]
[-0.04635148 -0.41126013  0.19178671  0.99477199]
Episode finished after 17 timesteps
[-0.00471904 -0.01423866 -0.02360322  0.04857936]
[-0.00500382 -0.20901434 -0.02263163  0.33372281]
[-0.0091841  -0.01357772 -0.01595718  0.03398981]
[-0.00945566 -0.20846724 -0.01527738  0.32159567]
[-0.013625   -0.40336834 -0.00884547  0.60942183]
[-0.02169237 -0.59836553  0.00334297  0.89930563]
[-0.03365968 -0.79353263  0.02132908  1.19303747]
[-0.04953033 -0.98892426  0.04518983  1.49232853]
[-0.06930882 -1.18456605  0.0750364   1.79877291]
[-0.09300014 -1.38044291  0.11101186  2.11380144]
[-0.120609   -1.57648491  0.15328789  2.43862482]
[-0.15213869 -1.38297129  0.20206039  2.19664835]
Episode finished after 12 timesteps
[-0.04236759 -0.01250491 -0.0450367  -0.00075991]
[-0.04261769 -0.206953   -0.0450519   0.27738016]
[-0.04675675 -0.01121824 -0.0395043  -0.02916485]
[-0.04698111 -0.20575207 -0.0400876   0.25079698]
[-0.05109615 -0.40027932 -0.

To better understand the environment, lets take a look at the possible actions and observations for the 'CartPole-v0' environment.  

In [ ]:
print(env.action_space)
print(env.observation_space)

The Discrete() space allows a fixed range of non-negative numbers.  In this case, valid actions are either 0 or 1.  The Box space represents an n-dimensional box.  Valid observations for this case will be an array of four numbers. We can also check the Box's bounds:

In [ ]:
print(env.observation_space.high)
print(env.observation_space.low)

## 2. Define Parameters

In [4]:
# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0 # Discount factor. Consideration of future rewards - same policies (the ones that balance the pole) are optimal 
          # at every step.
epsilon=1.0 # Exploration. Agent chooses action that it believes has the best long-term effect with probability 1- epsilon,
            # and it chooses an action uniformly at random, otherwise.  
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01 # the learning rate, determines to what extent the newly acquired information will override the old information. 
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

[2017-12-14 15:15:23,964] Making new env: CartPole-v0


## 2.1 Building the Neural Network

The following cells define the model we will be using.

In [5]:
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

## 2.2 Defining Necessary Functions

It is best practice to define common operations as functions.  The following operations will be used often, so we define a function for each.

In [6]:
def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

## 3. Defining Run Function

Lets define a function, run() that records the environment state and uses our network to choose the best action.  

In [7]:
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 100 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, epsilon)

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

## 4. Train the Network!

Here is the complete code together. Because Jupyter runs on a kernel, this code will work best if a single cell is used to run the entire code.

In [ ]:
import random
import gym
import math
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0
epsilon=1.0
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay    
        
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 20 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, get_epsilon(e))

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

run()

[2017-12-14 15:16:27,203] Making new env: CartPole-v0


[Episode 0] - Mean survival time over last 100 episodes was 38.0 ticks.
[Episode 20] - Mean survival time over last 100 episodes was 16.380952381 ticks.
[Episode 40] - Mean survival time over last 100 episodes was 33.8536585366 ticks.
[Episode 60] - Mean survival time over last 100 episodes was 51.131147541 ticks.
[Episode 80] - Mean survival time over last 100 episodes was 54.7160493827 ticks.
